- name: Deploy Configuration Template
  hosts: all
  gather_facts: no
  roles:
    - Juniper.junos
  
  tasks:

    - name: Retrive information from devices running Junos OS
      junos_facts:
        host: "{{ inventory_hostname }}"
      register: junos
      
    - name: Build interfaces configuration based on template
      template: src=./interfaces.j2 dest=./{{ inventory_hostname }}.conf

    - name: Deploy config to device ... please wait
      junos_config:
        src: "./{{ inventory_hostname }}.conf"
        update: merge
        comment: "Applied by Ansible"
      register: response

    - name: Print out the output
      debug: var=response
      
    - name: Get junos device information
      # juniper_junos_facts:
      junos_facts:
        gather_subset: config
        config_format: text
      register: result
    
    - debug: var=result

    - name: Save configuration to file in local directory
      copy: content="{{ result.ansible_facts.ansible_net_config }}" dest=./{{ inventory_hostname }}.save.conf