interfaces:
  - name: ge-0/0/3
    description: Connection to vMX1
    ip: 192.168.100.2
    peer: 192.168.100.1
    mask: 24
  - name: ge-0/0/1
    description: Connection1 to vMX3
    ip: 192.168.200.2
    peer: 192.168.200.1
    mask: 24
  - name: ge-0/0/2
    description: Connection2 to vMX3
    ip: 192.168.223.2
    peer: 192.168.223.1
    mask: 24
  - name: ge-0/0/0
    description: MGMT interface
    ip: 192.168.1.212
    mask: 24
  - name: lo0
    description: loopback interface
    ip: 2.2.2.2
    mask: 32